# Copyright 2020 The golang.design Initiative authors.
# All rights reserved. Use of this source code is governed
# by a GNU GPL-3.0 license that can be found in the LICENSE file.

version: "3"

services:
  code2img:
    container_name: code2img
    restart: always
    volumes:
      - ../data:/app/data
    image: code2img
    cap_add:
      - SYS_PTRACE # for debugging
    deploy:
      replicas: 1
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    external: true

